
/* #line 1 "lexer.rl" */
/*
 * Copyright Redis Ltd. 2016 - present
 * Licensed under your choice of the Redis Source Available License 2.0 (RSALv3) or
 * the Server Side Public License v1 (SSPLv1).
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>

#include "../parse.h"
#include "parser.h"
#include "../../query_node.h"
#include "../../stopwords.h"

/* forward declarations of stuff generated by lemon */

#define RSQuery_Parse_v3 RSQueryParser_v3_ // weird Lemon quirk.. oh well..
#define RSQuery_ParseAlloc_v3 RSQueryParser_v3_Alloc
#define RSQuery_ParseFree_v3 RSQueryParser_v3_Free

void RSQuery_Parse_v3(void *yyp, int yymajor, QueryToken yyminor, QueryParseCtx *ctx);
void *RSQuery_ParseAlloc_v3(void *(*mallocProc)(size_t));
void RSQuery_ParseFree_v3(void *p, void (*freeProc)(void *));


/* #line 353 "lexer.rl" */



/* #line 36 "lexer.c" */
static const char _query_actions[] = {
	0, 1, 0, 1, 1, 1, 2, 1, 
	14, 1, 15, 1, 16, 1, 17, 1, 
	18, 1, 19, 1, 20, 1, 21, 1, 
	22, 1, 23, 1, 24, 1, 25, 1, 
	26, 1, 27, 1, 28, 1, 29, 1, 
	30, 1, 31, 1, 32, 1, 33, 1, 
	34, 1, 35, 1, 36, 1, 37, 1, 
	38, 1, 39, 1, 40, 1, 41, 1, 
	42, 1, 43, 1, 44, 1, 45, 1, 
	46, 1, 47, 1, 48, 1, 49, 1, 
	50, 1, 51, 2, 2, 3, 2, 2, 
	4, 2, 2, 5, 2, 2, 6, 2, 
	2, 7, 2, 2, 8, 2, 2, 9, 
	2, 2, 10, 2, 2, 11, 2, 2, 
	12, 2, 2, 13
};

static const short _query_key_offsets[] = {
	0, 10, 20, 21, 23, 25, 26, 26, 
	28, 28, 31, 34, 36, 38, 39, 39, 
	49, 60, 61, 63, 65, 66, 66, 68, 
	70, 73, 75, 76, 77, 79, 82, 84, 
	94, 96, 98, 98, 100, 102, 102, 144, 
	155, 166, 177, 178, 181, 183, 184, 199, 
	210, 211, 217, 222, 225, 241, 253, 254, 
	257, 263, 268, 271, 287, 301, 314, 315, 
	325, 338, 348, 360, 372, 384
};

static const char _query_trans_keys[] = {
	9, 13, 32, 47, 58, 64, 91, 96, 
	123, 126, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 39, 39, 92, 39, 
	92, 41, 39, 92, 39, 92, 110, 39, 
	92, 102, 39, 92, 39, 92, 41, 9, 
	13, 32, 47, 58, 64, 91, 96, 123, 
	126, 40, 92, 96, 0, 47, 58, 64, 
	91, 94, 123, 127, 39, 39, 92, 39, 
	92, 41, 48, 57, 48, 57, 45, 48, 
	57, 48, 57, 110, 102, 48, 57, 45, 
	48, 57, 48, 57, 9, 13, 32, 47, 
	58, 64, 91, 96, 123, 126, 39, 92, 
	39, 92, 39, 92, 39, 92, 32, 34, 
	36, 37, 39, 40, 41, 42, 43, 45, 
	58, 59, 61, 64, 65, 91, 92, 93, 
	95, 97, 105, 114, 119, 123, 124, 125, 
	126, 127, 0, 8, 9, 13, 14, 31, 
	33, 47, 48, 57, 60, 63, 94, 96, 
	42, 92, 96, 0, 47, 58, 64, 91, 
	94, 123, 127, 40, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 42, 92, 
	96, 0, 47, 58, 64, 91, 94, 123, 
	127, 42, 39, 92, 105, 39, 92, 39, 
	36, 40, 45, 92, 96, 0, 47, 48, 
	57, 58, 64, 91, 94, 123, 127, 42, 
	92, 96, 0, 47, 58, 64, 91, 94, 
	123, 127, 42, 42, 46, 69, 101, 48, 
	57, 42, 69, 101, 48, 57, 42, 48, 
	57, 42, 46, 69, 92, 96, 101, 0, 
	47, 48, 57, 58, 64, 91, 94, 123, 
	127, 42, 45, 92, 96, 0, 47, 58, 
	64, 91, 94, 123, 127, 105, 105, 48, 
	57, 42, 46, 69, 101, 48, 57, 42, 
	69, 101, 48, 57, 42, 48, 57, 42, 
	46, 69, 92, 96, 101, 0, 47, 48, 
	57, 58, 64, 91, 94, 123, 127, 42, 
	45, 92, 96, 0, 47, 48, 57, 58, 
	64, 91, 94, 123, 127, 42, 92, 96, 
	0, 47, 48, 57, 58, 64, 91, 94, 
	123, 127, 62, 92, 96, 0, 47, 58, 
	64, 91, 94, 123, 127, 42, 83, 92, 
	96, 115, 0, 47, 58, 64, 91, 94, 
	123, 127, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 42, 92, 96, 110, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	42, 92, 96, 102, 0, 47, 58, 64, 
	91, 94, 123, 127, 39, 42, 92, 96, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	39, 42, 92, 96, 0, 47, 58, 64, 
	91, 94, 123, 127, 0
};

static const char _query_single_lengths[] = {
	0, 0, 1, 2, 2, 1, 0, 2, 
	0, 3, 3, 2, 2, 1, 0, 0, 
	3, 1, 2, 2, 1, 0, 0, 0, 
	1, 0, 1, 1, 0, 1, 0, 0, 
	2, 2, 0, 2, 2, 0, 28, 3, 
	3, 3, 1, 3, 2, 1, 5, 3, 
	1, 4, 3, 1, 6, 4, 1, 1, 
	4, 3, 1, 6, 4, 3, 1, 2, 
	5, 0, 4, 4, 4, 4
};

static const char _query_range_lengths[] = {
	5, 5, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 5, 
	4, 0, 0, 0, 0, 0, 1, 1, 
	1, 1, 0, 0, 1, 1, 1, 5, 
	0, 0, 0, 0, 0, 0, 7, 4, 
	4, 4, 0, 0, 0, 0, 5, 4, 
	0, 1, 1, 1, 5, 4, 0, 1, 
	1, 1, 1, 5, 5, 5, 0, 4, 
	4, 5, 4, 4, 4, 4
};

static const short _query_index_offsets[] = {
	0, 6, 12, 14, 17, 20, 22, 23, 
	26, 27, 31, 35, 38, 41, 43, 44, 
	50, 58, 60, 63, 66, 68, 69, 71, 
	73, 76, 78, 80, 82, 84, 87, 89, 
	95, 98, 101, 102, 105, 108, 109, 145, 
	153, 161, 169, 171, 175, 178, 180, 191, 
	199, 201, 207, 212, 215, 227, 236, 238, 
	241, 247, 252, 255, 267, 277, 286, 288, 
	295, 305, 311, 320, 329, 338
};

static const char _query_indicies[] = {
	1, 1, 1, 1, 1, 0, 2, 2, 
	2, 2, 2, 0, 4, 3, 3, 6, 
	5, 7, 6, 5, 8, 3, 5, 10, 
	11, 9, 9, 10, 11, 12, 9, 10, 
	11, 13, 9, 14, 16, 15, 17, 16, 
	15, 18, 14, 15, 19, 19, 19, 19, 
	19, 0, 21, 22, 20, 20, 20, 20, 
	20, 19, 23, 20, 20, 25, 24, 26, 
	25, 24, 27, 20, 24, 28, 20, 30, 
	29, 31, 32, 29, 32, 29, 33, 0, 
	34, 0, 35, 0, 37, 38, 36, 38, 
	0, 39, 39, 39, 39, 39, 0, 40, 
	42, 41, 43, 42, 41, 41, 40, 45, 
	44, 46, 45, 44, 44, 48, 50, 51, 
	52, 53, 54, 55, 56, 57, 58, 60, 
	61, 62, 63, 64, 65, 66, 67, 68, 
	64, 69, 70, 71, 72, 73, 74, 75, 
	47, 47, 48, 47, 49, 59, 49, 49, 
	1, 76, 77, 0, 0, 0, 0, 0, 
	1, 79, 80, 78, 78, 78, 78, 78, 
	2, 76, 80, 81, 81, 81, 81, 81, 
	2, 76, 0, 78, 11, 82, 9, 10, 
	11, 9, 85, 84, 87, 21, 88, 22, 
	86, 86, 89, 86, 86, 86, 19, 91, 
	22, 90, 90, 90, 90, 90, 19, 91, 
	90, 91, 92, 93, 93, 28, 90, 91, 
	93, 93, 30, 90, 91, 32, 90, 91, 
	92, 94, 22, 90, 94, 90, 89, 90, 
	90, 90, 19, 91, 31, 22, 90, 90, 
	90, 90, 90, 19, 95, 78, 95, 97, 
	96, 76, 99, 100, 100, 97, 98, 76, 
	100, 100, 35, 98, 76, 38, 98, 76, 
	99, 102, 77, 101, 102, 101, 59, 101, 
	101, 101, 1, 76, 37, 77, 103, 103, 
	104, 103, 103, 103, 1, 76, 77, 98, 
	98, 104, 98, 98, 98, 1, 105, 78, 
	106, 0, 0, 0, 0, 0, 39, 76, 
	107, 77, 103, 107, 103, 103, 103, 103, 
	1, 1, 1, 1, 1, 1, 78, 76, 
	77, 103, 108, 103, 103, 103, 103, 1, 
	76, 77, 103, 109, 103, 103, 103, 103, 
	1, 110, 76, 77, 103, 103, 103, 103, 
	103, 1, 111, 76, 77, 103, 103, 103, 
	103, 103, 1, 0
};

static const char _query_trans_targs[] = {
	38, 39, 41, 38, 3, 4, 6, 5, 
	42, 7, 38, 8, 10, 44, 38, 12, 
	14, 13, 42, 47, 38, 17, 15, 18, 
	19, 21, 20, 48, 49, 38, 50, 25, 
	51, 27, 38, 57, 38, 30, 58, 63, 
	38, 33, 34, 38, 36, 37, 38, 38, 
	38, 38, 38, 40, 38, 43, 45, 38, 
	46, 54, 55, 59, 38, 38, 62, 63, 
	64, 38, 65, 38, 39, 66, 68, 69, 
	38, 38, 38, 38, 38, 0, 38, 2, 
	1, 38, 9, 38, 38, 11, 38, 16, 
	22, 52, 38, 38, 23, 24, 53, 26, 
	38, 56, 38, 28, 29, 38, 60, 38, 
	61, 38, 31, 39, 67, 39, 32, 35
};

static const char _query_trans_actions[] = {
	81, 110, 92, 75, 0, 0, 0, 0, 
	92, 0, 43, 0, 0, 98, 71, 0, 
	0, 0, 110, 113, 73, 0, 0, 0, 
	0, 0, 0, 0, 5, 79, 5, 0, 
	0, 0, 9, 86, 69, 0, 0, 89, 
	77, 0, 0, 47, 0, 0, 45, 37, 
	33, 35, 11, 107, 27, 107, 5, 15, 
	104, 107, 101, 83, 21, 23, 0, 107, 
	110, 29, 0, 31, 107, 110, 110, 110, 
	17, 13, 19, 25, 39, 0, 63, 0, 
	0, 53, 0, 55, 57, 0, 61, 0, 
	0, 113, 67, 41, 0, 0, 113, 0, 
	59, 86, 51, 0, 0, 49, 110, 65, 
	86, 7, 0, 95, 110, 98, 0, 0
};

static const char _query_to_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 1, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0
};

static const char _query_from_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 3, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0
};

static const short _query_eof_trans[] = {
	1, 1, 4, 4, 4, 4, 4, 1, 
	1, 4, 4, 15, 15, 15, 15, 1, 
	21, 21, 21, 21, 21, 21, 21, 30, 
	30, 30, 1, 1, 1, 37, 1, 1, 
	41, 41, 41, 41, 41, 41, 0, 1, 
	79, 82, 1, 79, 84, 85, 87, 91, 
	91, 91, 91, 91, 91, 91, 79, 97, 
	99, 99, 99, 102, 104, 99, 79, 1, 
	104, 79, 104, 104, 104, 104
};

static const int query_start = 38;
static const int query_first_final = 38;
static const int query_error = -1;

static const int query_en_main = 38;


/* #line 356 "lexer.rl" */

QueryNode *RSQuery_ParseRaw_v3(QueryParseCtx *q) {
  void *pParser = RSQuery_ParseAlloc_v3(rm_malloc);

  
  int cs, act;
  const char* ts = q->raw;
  const char* te = q->raw + q->len;
  
/* #line 290 "lexer.c" */
	{
	cs = query_start;
	ts = 0;
	te = 0;
	act = 0;
	}

/* #line 365 "lexer.rl" */
  QueryToken tok = {.len = 0, .pos = 0, .s = 0};
  
  //parseCtx ctx = {.root = NULL, .ok = 1, .errorMsg = NULL, .q = q};
  const char* p = q->raw;
  const char* pe = q->raw + q->len;
  const char* eof = pe;
  
  
/* #line 307 "lexer.c" */
	{
	int _klen;
	unsigned int _trans;
	const char *_acts;
	unsigned int _nacts;
	const char *_keys;

	if ( p == pe )
		goto _test_eof;
_resume:
	_acts = _query_actions + _query_from_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 1:
/* #line 1 "NONE" */
	{ts = p;}
	break;
/* #line 326 "lexer.c" */
		}
	}

	_keys = _query_trans_keys + _query_key_offsets[cs];
	_trans = _query_index_offsets[cs];

	_klen = _query_single_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + _klen - 1;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( (*p) < *_mid )
				_upper = _mid - 1;
			else if ( (*p) > *_mid )
				_lower = _mid + 1;
			else {
				_trans += (unsigned int)(_mid - _keys);
				goto _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _query_range_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + (_klen<<1) - 2;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( (*p) < _mid[0] )
				_upper = _mid - 2;
			else if ( (*p) > _mid[1] )
				_lower = _mid + 2;
			else {
				_trans += (unsigned int)((_mid - _keys)>>1);
				goto _match;
			}
		}
		_trans += _klen;
	}

_match:
	_trans = _query_indicies[_trans];
_eof_trans:
	cs = _query_trans_targs[_trans];

	if ( _query_trans_actions[_trans] == 0 )
		goto _again;

	_acts = _query_actions + _query_trans_actions[_trans];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 )
	{
		switch ( *_acts++ )
		{
	case 2:
/* #line 1 "NONE" */
	{te = p+1;}
	break;
	case 3:
/* #line 70 "lexer.rl" */
	{act = 1;}
	break;
	case 4:
/* #line 81 "lexer.rl" */
	{act = 2;}
	break;
	case 5:
/* #line 92 "lexer.rl" */
	{act = 3;}
	break;
	case 6:
/* #line 102 "lexer.rl" */
	{act = 4;}
	break;
	case 7:
/* #line 121 "lexer.rl" */
	{act = 6;}
	break;
	case 8:
/* #line 130 "lexer.rl" */
	{act = 7;}
	break;
	case 9:
/* #line 199 "lexer.rl" */
	{act = 16;}
	break;
	case 10:
/* #line 213 "lexer.rl" */
	{act = 18;}
	break;
	case 11:
/* #line 242 "lexer.rl" */
	{act = 23;}
	break;
	case 12:
/* #line 245 "lexer.rl" */
	{act = 25;}
	break;
	case 13:
/* #line 281 "lexer.rl" */
	{act = 28;}
	break;
	case 14:
/* #line 112 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts+1;
    RSQuery_Parse_v3(pParser, ARROW, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 15:
/* #line 130 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 16:
/* #line 141 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, QUOTE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 17:
/* #line 148 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, OR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 18:
/* #line 163 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, RP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 19:
/* #line 170 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 20:
/* #line 177 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 21:
/* #line 184 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 22:
/* #line 191 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v3(pParser, SEMICOLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 23:
/* #line 206 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, TILDE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 24:
/* #line 220 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, PERCENT, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 25:
/* #line 227 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, LSQB, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }  
  }}
	break;
	case 26:
/* #line 234 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, RSQB, tok, q);   
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    } 
  }}
	break;
	case 27:
/* #line 241 "lexer.rl" */
	{te = p+1;}
	break;
	case 28:
/* #line 242 "lexer.rl" */
	{te = p+1;}
	break;
	case 29:
/* #line 243 "lexer.rl" */
	{te = p+1;}
	break;
	case 30:
/* #line 267 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*ts == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v3(pParser, PREFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 31:
/* #line 295 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v3(pParser, CONTAINS, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 32:
/* #line 310 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    printf("verbatim: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, VERBATIM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 33:
/* #line 324 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_WILDCARD : QT_WILDCARD;
    tok.pos = ts-q->raw + 2;
    tok.len = te - (ts + 3 + is_attr);
    tok.s = ts + 2 + is_attr;
    tok.numval = 0;
    printf("wildcard: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, WILDCARD, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 34:
/* #line 338 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_RAW_STRING : QT_RAW_STRING;
    tok.pos = ts-q->raw + 2;
    tok.len = te - (ts + 3 + is_attr);
    tok.s = ts + 2 + is_attr;
    tok.numval = 0;
    printf("raw_string: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, RAW_STRING, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 35:
/* #line 70 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 36:
/* #line 81 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 37:
/* #line 102 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    printf("attr: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 38:
/* #line 130 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 39:
/* #line 155 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, LP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 40:
/* #line 199 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 41:
/* #line 213 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 42:
/* #line 242 "lexer.rl" */
	{te = p;p--;}
	break;
	case 43:
/* #line 245 "lexer.rl" */
	{te = p;p--;{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 44:
/* #line 281 "lexer.rl" */
	{te = p;p--;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v3(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 45:
/* #line 81 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 46:
/* #line 155 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, LP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 47:
/* #line 213 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 48:
/* #line 242 "lexer.rl" */
	{{p = ((te))-1;}}
	break;
	case 49:
/* #line 245 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 50:
/* #line 281 "lexer.rl" */
	{{p = ((te))-1;}{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v3(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 51:
/* #line 1 "NONE" */
	{	switch( act ) {
	case 1:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 2:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 3:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    printf("mod: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, MODIFIER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 4:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    printf("attr: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 6:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, AS_T, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 7:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 16:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 18:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 25:
	{{p = ((te))-1;}
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 28:
	{{p = ((te))-1;}
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v3(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	default:
	{{p = ((te))-1;}}
	break;
	}
	}
	break;
/* #line 986 "lexer.c" */
		}
	}

_again:
	_acts = _query_actions + _query_to_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 0:
/* #line 1 "NONE" */
	{ts = 0;}
	break;
/* #line 999 "lexer.c" */
		}
	}

	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	if ( _query_eof_trans[cs] > 0 ) {
		_trans = _query_eof_trans[cs] - 1;
		goto _eof_trans;
	}
	}

	_out: {}
	}

/* #line 373 "lexer.rl" */
  
  if (QPCTX_ISOK(q)) {
    RSQuery_Parse_v3(pParser, 0, tok, q);
  }
  RSQuery_ParseFree_v3(pParser, rm_free);
  if (!QPCTX_ISOK(q) && q->root) {
    QueryNode_Free(q->root);
    q->root = NULL;
  }
  return q->root;
}

