
/* #line 1 "lexer.rl" */
/*
 * Copyright Redis Ltd. 2016 - present
 * Licensed under your choice of the Redis Source Available License 2.0 (RSALv3) or
 * the Server Side Public License v1 (SSPLv1).
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>

#include "../parse.h"
#include "parser.h"
#include "../../query_node.h"
#include "../../stopwords.h"

/* forward declarations of stuff generated by lemon */

#define RSQuery_Parse_v3 RSQueryParser_v3_ // weird Lemon quirk.. oh well..
#define RSQuery_ParseAlloc_v3 RSQueryParser_v3_Alloc
#define RSQuery_ParseFree_v3 RSQueryParser_v3_Free

void RSQuery_Parse_v3(void *yyp, int yymajor, QueryToken yyminor, QueryParseCtx *ctx);
void *RSQuery_ParseAlloc_v3(void *(*mallocProc)(size_t));
void RSQuery_ParseFree_v3(void *p, void (*freeProc)(void *));


/* verbatim = squote . ((any - squote - escape) | escape.any)+ . squote $4; */
  // verbatim => {
  //   int is_attr = (*(ts+2) == '$') ? 1 : 0;
  //   tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
  //   tok.pos = ts-q->raw;
  //   tok.len = te - (ts + 2 + is_attr);
  //   tok.s = ts + 1 + is_attr;
  //   tok.numval = 0;
  //   printf("verbatim: %.*s\n", (int)tok.len, tok.s);
  //   RSQuery_Parse_v3(pParser, VERBATIM, tok, q);
  //   if (!QPCTX_ISOK(q)) {
  //     fbreak;
  //   }
  // };


  //   verbatim_tag_term => {
  //   tok.len = te - ( ts + 4);
  //   tok.s = ts + 2;
  //   tok.numval = 0;
  //   tok.pos = ts-q->raw;
  //   printf("verbatim_tag_term: %.*s\n", (int)tok.len, tok.s);
  //   printf("TODO: This should send a verbatim_tag_term, to be processed as TAG, but I still get a Syntax Error.\n");
  //   RSQuery_Parse_v3(pParser, TERM, tok, q);
  //   if (!QPCTX_ISOK(q)) {
  //     printf("Nafraf: Syntax Error verbatim_tag_term\n");
  //     fbreak;
  //   }
  // };


/* #line 413 "lexer.rl" */



/* #line 67 "lexer.c" */
static const char _query_actions[] = {
	0, 1, 0, 1, 1, 1, 2, 1, 
	16, 1, 17, 1, 18, 1, 19, 1, 
	20, 1, 21, 1, 22, 1, 23, 1, 
	24, 1, 25, 1, 26, 1, 27, 1, 
	28, 1, 29, 1, 30, 1, 31, 1, 
	32, 1, 33, 1, 34, 1, 35, 1, 
	36, 1, 37, 1, 38, 1, 39, 1, 
	40, 1, 41, 1, 42, 1, 43, 1, 
	44, 1, 45, 1, 46, 1, 47, 1, 
	48, 1, 49, 1, 50, 1, 51, 1, 
	52, 1, 53, 1, 54, 1, 55, 2, 
	2, 3, 2, 2, 4, 2, 2, 5, 
	2, 2, 6, 2, 2, 7, 2, 2, 
	8, 2, 2, 9, 2, 2, 10, 2, 
	2, 11, 2, 2, 12, 2, 2, 13, 
	2, 2, 14, 2, 2, 15
};

static const short _query_key_offsets[] = {
	0, 10, 20, 23, 24, 26, 26, 29, 
	32, 33, 43, 54, 57, 58, 60, 62, 
	65, 67, 68, 69, 71, 74, 76, 86, 
	88, 90, 90, 92, 94, 94, 136, 147, 
	158, 169, 170, 173, 175, 178, 193, 204, 
	205, 211, 216, 219, 235, 247, 248, 251, 
	257, 262, 265, 281, 295, 308, 309, 319, 
	332, 342, 354, 366, 378
};

static const char _query_trans_keys[] = {
	9, 13, 32, 47, 58, 64, 91, 96, 
	123, 126, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 32, 9, 13, 41, 
	39, 92, 39, 92, 110, 39, 92, 102, 
	41, 9, 13, 32, 47, 58, 64, 91, 
	96, 123, 126, 40, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 32, 9, 
	13, 41, 48, 57, 48, 57, 45, 48, 
	57, 48, 57, 110, 102, 48, 57, 45, 
	48, 57, 48, 57, 9, 13, 32, 47, 
	58, 64, 91, 96, 123, 126, 39, 92, 
	39, 92, 39, 92, 39, 92, 32, 34, 
	36, 37, 39, 40, 41, 42, 43, 45, 
	58, 59, 61, 64, 65, 91, 92, 93, 
	95, 97, 105, 114, 119, 123, 124, 125, 
	126, 127, 0, 8, 9, 13, 14, 31, 
	33, 47, 48, 57, 60, 63, 94, 96, 
	42, 92, 96, 0, 47, 58, 64, 91, 
	94, 123, 127, 40, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 42, 92, 
	96, 0, 47, 58, 64, 91, 94, 123, 
	127, 42, 39, 92, 105, 39, 92, 32, 
	9, 13, 36, 40, 45, 92, 96, 0, 
	47, 48, 57, 58, 64, 91, 94, 123, 
	127, 42, 92, 96, 0, 47, 58, 64, 
	91, 94, 123, 127, 42, 42, 46, 69, 
	101, 48, 57, 42, 69, 101, 48, 57, 
	42, 48, 57, 42, 46, 69, 92, 96, 
	101, 0, 47, 48, 57, 58, 64, 91, 
	94, 123, 127, 42, 45, 92, 96, 0, 
	47, 58, 64, 91, 94, 123, 127, 105, 
	105, 48, 57, 42, 46, 69, 101, 48, 
	57, 42, 69, 101, 48, 57, 42, 48, 
	57, 42, 46, 69, 92, 96, 101, 0, 
	47, 48, 57, 58, 64, 91, 94, 123, 
	127, 42, 45, 92, 96, 0, 47, 48, 
	57, 58, 64, 91, 94, 123, 127, 42, 
	92, 96, 0, 47, 48, 57, 58, 64, 
	91, 94, 123, 127, 62, 92, 96, 0, 
	47, 58, 64, 91, 94, 123, 127, 42, 
	83, 92, 96, 115, 0, 47, 58, 64, 
	91, 94, 123, 127, 9, 13, 32, 47, 
	58, 64, 91, 96, 123, 126, 42, 92, 
	96, 110, 0, 47, 58, 64, 91, 94, 
	123, 127, 42, 92, 96, 102, 0, 47, 
	58, 64, 91, 94, 123, 127, 39, 42, 
	92, 96, 0, 47, 58, 64, 91, 94, 
	123, 127, 39, 42, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 0
};

static const char _query_single_lengths[] = {
	0, 0, 1, 1, 2, 0, 3, 3, 
	1, 0, 3, 1, 1, 0, 0, 1, 
	0, 1, 1, 0, 1, 0, 0, 2, 
	2, 0, 2, 2, 0, 28, 3, 3, 
	3, 1, 3, 2, 1, 5, 3, 1, 
	4, 3, 1, 6, 4, 1, 1, 4, 
	3, 1, 6, 4, 3, 1, 2, 5, 
	0, 4, 4, 4, 4
};

static const char _query_range_lengths[] = {
	5, 5, 1, 0, 0, 0, 0, 0, 
	0, 5, 4, 1, 0, 1, 1, 1, 
	1, 0, 0, 1, 1, 1, 5, 0, 
	0, 0, 0, 0, 0, 7, 4, 4, 
	4, 0, 0, 0, 1, 5, 4, 0, 
	1, 1, 1, 5, 4, 0, 1, 1, 
	1, 1, 5, 5, 5, 0, 4, 4, 
	5, 4, 4, 4, 4
};

static const short _query_index_offsets[] = {
	0, 6, 12, 15, 17, 20, 21, 25, 
	29, 31, 37, 45, 48, 50, 52, 54, 
	57, 59, 61, 63, 65, 68, 70, 76, 
	79, 82, 83, 86, 89, 90, 126, 134, 
	142, 150, 152, 156, 159, 162, 173, 181, 
	183, 189, 194, 197, 209, 218, 220, 223, 
	229, 234, 237, 249, 259, 268, 270, 277, 
	287, 293, 302, 311, 320
};

static const char _query_indicies[] = {
	1, 1, 1, 1, 1, 0, 2, 2, 
	2, 2, 2, 0, 4, 4, 3, 5, 
	3, 7, 8, 6, 6, 7, 8, 10, 
	6, 7, 8, 11, 6, 13, 12, 14, 
	14, 14, 14, 14, 0, 16, 17, 15, 
	15, 15, 15, 15, 14, 18, 18, 15, 
	19, 15, 20, 15, 22, 21, 23, 24, 
	21, 24, 21, 25, 0, 26, 0, 27, 
	0, 29, 30, 28, 30, 0, 31, 31, 
	31, 31, 31, 0, 32, 34, 33, 35, 
	34, 33, 33, 32, 37, 36, 38, 37, 
	36, 36, 40, 42, 43, 44, 45, 46, 
	47, 48, 49, 50, 52, 53, 54, 55, 
	56, 57, 58, 59, 60, 56, 61, 62, 
	63, 64, 65, 66, 67, 39, 39, 40, 
	39, 41, 51, 41, 41, 1, 68, 69, 
	0, 0, 0, 0, 0, 1, 71, 72, 
	70, 70, 70, 70, 70, 2, 68, 72, 
	73, 73, 73, 73, 73, 2, 68, 0, 
	74, 8, 75, 6, 7, 8, 6, 78, 
	78, 77, 80, 16, 81, 17, 79, 79, 
	82, 79, 79, 79, 14, 84, 17, 83, 
	83, 83, 83, 83, 14, 84, 83, 84, 
	85, 86, 86, 20, 83, 84, 86, 86, 
	22, 83, 84, 24, 83, 84, 85, 87, 
	17, 83, 87, 83, 82, 83, 83, 83, 
	14, 84, 23, 17, 83, 83, 83, 83, 
	83, 14, 88, 70, 88, 90, 89, 68, 
	92, 93, 93, 90, 91, 68, 93, 93, 
	27, 91, 68, 30, 91, 68, 92, 95, 
	69, 94, 95, 94, 51, 94, 94, 94, 
	1, 68, 29, 69, 96, 96, 97, 96, 
	96, 96, 1, 68, 69, 91, 91, 97, 
	91, 91, 91, 1, 98, 70, 99, 0, 
	0, 0, 0, 0, 31, 68, 100, 69, 
	96, 100, 96, 96, 96, 96, 1, 1, 
	1, 1, 1, 1, 70, 68, 69, 96, 
	101, 96, 96, 96, 96, 1, 68, 69, 
	96, 102, 96, 96, 96, 96, 1, 103, 
	68, 69, 96, 96, 96, 96, 96, 1, 
	104, 68, 69, 96, 96, 96, 96, 96, 
	1, 0
};

static const char _query_trans_targs[] = {
	29, 30, 32, 29, 3, 33, 4, 29, 
	5, 29, 7, 35, 29, 33, 38, 29, 
	11, 9, 12, 39, 40, 29, 41, 16, 
	42, 18, 29, 48, 29, 21, 49, 54, 
	29, 24, 25, 29, 27, 28, 29, 29, 
	29, 29, 29, 31, 29, 34, 36, 29, 
	37, 45, 46, 50, 29, 29, 53, 54, 
	55, 29, 56, 29, 30, 57, 59, 60, 
	29, 29, 29, 29, 29, 0, 29, 2, 
	1, 29, 29, 6, 29, 29, 8, 29, 
	10, 13, 43, 29, 29, 14, 15, 44, 
	17, 29, 47, 29, 19, 20, 29, 51, 
	29, 52, 29, 22, 30, 58, 30, 23, 
	26
};

static const char _query_trans_actions[] = {
	85, 120, 96, 79, 0, 96, 0, 45, 
	0, 75, 0, 102, 73, 117, 123, 77, 
	0, 0, 0, 0, 5, 83, 5, 0, 
	0, 0, 9, 90, 71, 0, 0, 93, 
	81, 0, 0, 47, 0, 0, 43, 37, 
	33, 35, 11, 114, 27, 105, 5, 15, 
	111, 114, 108, 87, 21, 23, 0, 114, 
	120, 29, 0, 31, 114, 120, 120, 120, 
	17, 13, 19, 25, 39, 0, 65, 0, 
	0, 53, 59, 0, 55, 57, 0, 63, 
	0, 0, 123, 69, 41, 0, 0, 123, 
	0, 61, 90, 51, 0, 0, 49, 120, 
	67, 90, 7, 0, 99, 120, 102, 0, 
	0
};

static const char _query_to_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 1, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0
};

static const char _query_from_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 3, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0
};

static const short _query_eof_trans[] = {
	1, 1, 4, 4, 1, 1, 10, 10, 
	13, 1, 16, 16, 16, 16, 22, 22, 
	22, 1, 1, 1, 29, 1, 1, 33, 
	33, 33, 33, 33, 33, 0, 1, 71, 
	74, 1, 75, 77, 78, 80, 84, 84, 
	84, 84, 84, 84, 84, 71, 90, 92, 
	92, 92, 95, 97, 92, 71, 1, 97, 
	71, 97, 97, 97, 97
};

static const int query_start = 29;
static const int query_first_final = 29;
static const int query_error = -1;

static const int query_en_main = 29;


/* #line 416 "lexer.rl" */

QueryNode *RSQuery_ParseRaw_v3(QueryParseCtx *q) {
  void *pParser = RSQuery_ParseAlloc_v3(rm_malloc);

  
  int cs, act;
  const char* ts = q->raw;
  const char* te = q->raw + q->len;
  
/* #line 312 "lexer.c" */
	{
	cs = query_start;
	ts = 0;
	te = 0;
	act = 0;
	}

/* #line 425 "lexer.rl" */
  QueryToken tok = {.len = 0, .pos = 0, .s = 0};
  
  //parseCtx ctx = {.root = NULL, .ok = 1, .errorMsg = NULL, .q = q};
  const char* p = q->raw;
  const char* pe = q->raw + q->len;
  const char* eof = pe;
  
  
/* #line 329 "lexer.c" */
	{
	int _klen;
	unsigned int _trans;
	const char *_acts;
	unsigned int _nacts;
	const char *_keys;

	if ( p == pe )
		goto _test_eof;
_resume:
	_acts = _query_actions + _query_from_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 1:
/* #line 1 "NONE" */
	{ts = p;}
	break;
/* #line 348 "lexer.c" */
		}
	}

	_keys = _query_trans_keys + _query_key_offsets[cs];
	_trans = _query_index_offsets[cs];

	_klen = _query_single_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + _klen - 1;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( (*p) < *_mid )
				_upper = _mid - 1;
			else if ( (*p) > *_mid )
				_lower = _mid + 1;
			else {
				_trans += (unsigned int)(_mid - _keys);
				goto _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _query_range_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + (_klen<<1) - 2;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( (*p) < _mid[0] )
				_upper = _mid - 2;
			else if ( (*p) > _mid[1] )
				_lower = _mid + 2;
			else {
				_trans += (unsigned int)((_mid - _keys)>>1);
				goto _match;
			}
		}
		_trans += _klen;
	}

_match:
	_trans = _query_indicies[_trans];
_eof_trans:
	cs = _query_trans_targs[_trans];

	if ( _query_trans_actions[_trans] == 0 )
		goto _again;

	_acts = _query_actions + _query_trans_actions[_trans];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 )
	{
		switch ( *_acts++ )
		{
	case 2:
/* #line 1 "NONE" */
	{te = p+1;}
	break;
	case 3:
/* #line 106 "lexer.rl" */
	{act = 1;}
	break;
	case 4:
/* #line 117 "lexer.rl" */
	{act = 2;}
	break;
	case 5:
/* #line 128 "lexer.rl" */
	{act = 3;}
	break;
	case 6:
/* #line 138 "lexer.rl" */
	{act = 4;}
	break;
	case 7:
/* #line 157 "lexer.rl" */
	{act = 6;}
	break;
	case 8:
/* #line 166 "lexer.rl" */
	{act = 7;}
	break;
	case 9:
/* #line 235 "lexer.rl" */
	{act = 16;}
	break;
	case 10:
/* #line 244 "lexer.rl" */
	{act = 17;}
	break;
	case 11:
/* #line 258 "lexer.rl" */
	{act = 19;}
	break;
	case 12:
/* #line 287 "lexer.rl" */
	{act = 24;}
	break;
	case 13:
/* #line 292 "lexer.rl" */
	{act = 26;}
	break;
	case 14:
/* #line 305 "lexer.rl" */
	{act = 27;}
	break;
	case 15:
/* #line 341 "lexer.rl" */
	{act = 30;}
	break;
	case 16:
/* #line 148 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts+1;
    RSQuery_Parse_v3(pParser, ARROW, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 17:
/* #line 166 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 18:
/* #line 177 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, QUOTE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 19:
/* #line 184 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, OR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 20:
/* #line 199 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, RP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 21:
/* #line 206 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 22:
/* #line 213 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 23:
/* #line 220 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v3(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 24:
/* #line 227 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v3(pParser, SEMICOLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 25:
/* #line 251 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, TILDE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 26:
/* #line 265 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, PERCENT, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 27:
/* #line 272 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, LSQB, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }  
  }}
	break;
	case 28:
/* #line 279 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, RSQB, tok, q);   
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    } 
  }}
	break;
	case 29:
/* #line 286 "lexer.rl" */
	{te = p+1;}
	break;
	case 30:
/* #line 287 "lexer.rl" */
	{te = p+1;}
	break;
	case 31:
/* #line 288 "lexer.rl" */
	{te = p+1;}
	break;
	case 32:
/* #line 327 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*ts == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v3(pParser, PREFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 33:
/* #line 355 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v3(pParser, CONTAINS, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 34:
/* #line 371 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_WILDCARD : QT_WILDCARD;
    tok.pos = ts-q->raw + 2;
    tok.len = te - (ts + 3 + is_attr);
    tok.s = ts + 2 + is_attr;
    tok.numval = 0;
    printf("wildcard: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, WILDCARD, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 35:
/* #line 385 "lexer.rl" */
	{te = p+1;{
    tok.type = QT_RAW_STRING;
    tok.pos = ts-q->raw + 1;
    tok.len = te - (ts + 2);
    tok.s = ts + 1;
    tok.numval = 0;
    printf("raw_string: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, RAW_STRING, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 36:
/* #line 398 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_RAW_STRING : QT_RAW_STRING;
    tok.pos = ts-q->raw + 2;
    tok.len = te - (ts + 3 + is_attr);
    tok.s = ts + 2 + is_attr;
    tok.numval = 0;
    printf("raw_string2: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, RAW_STRING, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 37:
/* #line 106 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 38:
/* #line 117 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 39:
/* #line 138 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    printf("attr: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 40:
/* #line 166 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 41:
/* #line 191 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, LP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 42:
/* #line 235 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    printf("squote: %.*s\n", (int)(te-ts), ts);
    RSQuery_Parse_v3(pParser, SQUOTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 43:
/* #line 244 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 44:
/* #line 258 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 45:
/* #line 287 "lexer.rl" */
	{te = p;p--;}
	break;
	case 46:
/* #line 305 "lexer.rl" */
	{te = p;p--;{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 47:
/* #line 341 "lexer.rl" */
	{te = p;p--;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v3(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 48:
/* #line 117 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 49:
/* #line 191 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, LP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 50:
/* #line 235 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.pos = ts-q->raw;
    printf("squote: %.*s\n", (int)(te-ts), ts);
    RSQuery_Parse_v3(pParser, SQUOTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 51:
/* #line 258 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 52:
/* #line 287 "lexer.rl" */
	{{p = ((te))-1;}}
	break;
	case 53:
/* #line 305 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 54:
/* #line 341 "lexer.rl" */
	{{p = ((te))-1;}{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v3(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 55:
/* #line 1 "NONE" */
	{	switch( act ) {
	case 1:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 2:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 3:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    printf("mod: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, MODIFIER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 4:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    printf("attr: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 6:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts;
    RSQuery_Parse_v3(pParser, AS_T, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 7:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v3(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 16:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    printf("squote: %.*s\n", (int)(te-ts), ts);
    RSQuery_Parse_v3(pParser, SQUOTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 17:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 19:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    RSQuery_Parse_v3(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 26:
	{{p = ((te))-1;}
    tok.len = te - ( ts + 2);
    tok.s = ts + 1;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("verbatim_txt_term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, VERBATIM, tok, q);
    if (!QPCTX_ISOK(q)) {
      printf("Nafraf: Syntax Error\n");
      {p++; goto _out; }
    }
  }
	break;
	case 27:
	{{p = ((te))-1;}
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v3(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 30:
	{{p = ((te))-1;}
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v3(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	default:
	{{p = ((te))-1;}}
	break;
	}
	}
	break;
/* #line 1061 "lexer.c" */
		}
	}

_again:
	_acts = _query_actions + _query_to_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 0:
/* #line 1 "NONE" */
	{ts = 0;}
	break;
/* #line 1074 "lexer.c" */
		}
	}

	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	if ( _query_eof_trans[cs] > 0 ) {
		_trans = _query_eof_trans[cs] - 1;
		goto _eof_trans;
	}
	}

	_out: {}
	}

/* #line 433 "lexer.rl" */
  
  if (QPCTX_ISOK(q)) {
    RSQuery_Parse_v3(pParser, 0, tok, q);
  }
  RSQuery_ParseFree_v3(pParser, rm_free);
  if (!QPCTX_ISOK(q) && q->root) {
    QueryNode_Free(q->root);
    q->root = NULL;
  }
  return q->root;
}

