
/* #line 1 "lexer.rl" */
/*
 * Copyright Redis Ltd. 2016 - present
 * Licensed under your choice of the Redis Source Available License 2.0 (RSALv2) or
 * the Server Side Public License v1 (SSPLv1).
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>

#include "../parse.h"
#include "parser.h"
#include "../../query_node.h"
#include "../../stopwords.h"

/* forward declarations of stuff generated by lemon */

#define RSQuery_Parse_v2 RSQueryParser_v2_ // weird Lemon quirk.. oh well..
#define RSQuery_ParseAlloc_v2 RSQueryParser_v2_Alloc
#define RSQuery_ParseFree_v2 RSQueryParser_v2_Free

void RSQuery_Parse_v2(void *yyp, int yymajor, QueryToken yyminor, QueryParseCtx *ctx);
void *RSQuery_ParseAlloc_v2(void *(*mallocProc)(size_t));
void RSQuery_ParseFree_v2(void *p, void (*freeProc)(void *));


/* #line 327 "lexer.rl" */



/* #line 36 "lexer.c" */
static const char _query_actions[] = {
	0, 1, 2, 1, 3, 1, 26, 1, 
	27, 1, 28, 1, 29, 1, 30, 1, 
	31, 1, 32, 1, 33, 1, 34, 1, 
	35, 1, 36, 1, 37, 1, 38, 1, 
	39, 1, 40, 1, 41, 1, 42, 1, 
	43, 1, 44, 1, 45, 1, 46, 1, 
	47, 1, 48, 2, 0, 1, 2, 3, 
	4, 2, 3, 5, 2, 3, 6, 2, 
	3, 7, 2, 3, 8, 2, 3, 9, 
	2, 3, 10, 2, 3, 11, 2, 3, 
	12, 2, 3, 13, 2, 3, 14, 2, 
	3, 15, 2, 3, 16, 2, 3, 17, 
	2, 3, 18, 2, 3, 19, 2, 3, 
	20, 2, 3, 21, 2, 3, 22, 2, 
	3, 23, 2, 3, 24, 2, 3, 25
	
};

static const short _query_key_offsets[] = {
	0, 0, 19, 22, 35, 46, 56, 69, 
	79, 81, 81, 84, 97, 107, 117, 127, 
	129, 132, 134, 136, 139, 141, 151, 172, 
	186, 206, 226, 228, 230, 230, 272, 291, 
	307, 326, 345, 356, 374, 391, 409, 427, 
	449, 468, 479, 490, 508, 528, 533, 536, 
	554, 572, 590, 613, 632, 649, 666, 683, 
	702, 722, 727, 730, 748, 766, 784, 807, 
	828, 849, 866, 876, 902
};

static const char _query_trans_keys[] = {
	32, 42, 44, 58, 64, 92, 96, 0, 
	39, 40, 45, 46, 47, 59, 63, 91, 
	94, 123, 127, 92, 124, 125, 92, 123, 
	126, 9, 13, 32, 47, 58, 64, 91, 
	96, 124, 125, 42, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 9, 13, 
	32, 47, 58, 64, 91, 96, 123, 126, 
	92, 123, 126, 9, 13, 32, 47, 58, 
	64, 91, 96, 124, 125, 9, 13, 32, 
	47, 58, 64, 91, 96, 123, 126, 39, 
	92, 92, 124, 125, 92, 123, 126, 9, 
	13, 32, 47, 58, 64, 91, 96, 124, 
	125, 9, 13, 32, 47, 58, 64, 91, 
	96, 123, 126, 92, 96, 0, 47, 58, 
	64, 91, 94, 123, 127, 9, 13, 32, 
	47, 58, 64, 91, 96, 123, 126, 48, 
	57, 45, 48, 57, 48, 57, 48, 57, 
	45, 48, 57, 48, 57, 9, 13, 32, 
	47, 58, 64, 91, 96, 123, 126, 32, 
	42, 44, 58, 64, 83, 92, 96, 115, 
	0, 39, 40, 45, 46, 47, 59, 63, 
	91, 94, 123, 127, 42, 92, 96, 123, 
	0, 47, 58, 64, 91, 94, 124, 125, 
	126, 127, 32, 42, 44, 58, 64, 92, 
	96, 110, 0, 39, 40, 45, 46, 47, 
	59, 63, 91, 94, 123, 127, 32, 39, 
	42, 44, 58, 64, 92, 96, 0, 38, 
	40, 45, 46, 47, 59, 63, 91, 94, 
	123, 127, 39, 92, 39, 92, 32, 34, 
	36, 37, 39, 40, 41, 42, 43, 44, 
	45, 58, 59, 61, 64, 65, 91, 92, 
	93, 95, 97, 105, 119, 123, 124, 125, 
	126, 127, 0, 8, 9, 13, 14, 31, 
	33, 47, 48, 57, 60, 63, 94, 96, 
	32, 42, 44, 58, 64, 92, 96, 0, 
	39, 40, 45, 46, 47, 59, 63, 91, 
	94, 123, 127, 42, 44, 92, 96, 0, 
	31, 33, 39, 46, 47, 59, 63, 91, 
	94, 123, 127, 32, 42, 44, 58, 64, 
	92, 96, 0, 39, 40, 45, 46, 47, 
	59, 63, 91, 94, 123, 127, 32, 42, 
	44, 58, 64, 92, 96, 0, 39, 40, 
	45, 46, 47, 59, 63, 91, 94, 123, 
	127, 42, 92, 96, 0, 47, 58, 64, 
	91, 94, 123, 127, 39, 42, 44, 92, 
	96, 105, 0, 31, 33, 38, 46, 47, 
	59, 63, 91, 94, 123, 127, 39, 42, 
	44, 92, 96, 0, 31, 33, 38, 46, 
	47, 59, 63, 91, 94, 123, 127, 39, 
	42, 44, 92, 96, 110, 0, 31, 33, 
	38, 46, 47, 59, 63, 91, 94, 123, 
	127, 39, 42, 44, 92, 96, 102, 0, 
	31, 33, 38, 46, 47, 59, 63, 91, 
	94, 123, 127, 32, 36, 42, 45, 58, 
	64, 92, 96, 0, 39, 40, 43, 44, 
	47, 48, 57, 59, 63, 91, 94, 123, 
	127, 32, 42, 44, 58, 64, 92, 96, 
	0, 39, 40, 45, 46, 47, 59, 63, 
	91, 94, 123, 127, 42, 92, 96, 0, 
	47, 58, 64, 91, 94, 123, 127, 42, 
	92, 96, 0, 47, 58, 64, 91, 94, 
	123, 127, 42, 44, 92, 96, 0, 31, 
	33, 39, 46, 47, 48, 57, 59, 63, 
	91, 94, 123, 127, 42, 44, 46, 47, 
	69, 92, 96, 101, 0, 31, 33, 39, 
	48, 57, 59, 63, 91, 94, 123, 127, 
	42, 69, 101, 48, 57, 42, 48, 57, 
	42, 45, 92, 96, 0, 31, 33, 39, 
	44, 47, 48, 57, 59, 63, 91, 94, 
	123, 127, 42, 44, 92, 96, 0, 31, 
	33, 39, 46, 47, 48, 57, 59, 63, 
	91, 94, 123, 127, 42, 44, 92, 96, 
	0, 31, 33, 39, 46, 47, 48, 57, 
	59, 63, 91, 94, 123, 127, 32, 42, 
	44, 46, 47, 58, 64, 69, 92, 96, 
	101, 0, 39, 40, 45, 48, 57, 59, 
	63, 91, 94, 123, 127, 32, 42, 45, 
	58, 64, 92, 96, 0, 39, 40, 43, 
	44, 47, 59, 63, 91, 94, 123, 127, 
	42, 44, 92, 96, 105, 0, 31, 33, 
	39, 46, 47, 59, 63, 91, 94, 123, 
	127, 42, 44, 92, 96, 110, 0, 31, 
	33, 39, 46, 47, 59, 63, 91, 94, 
	123, 127, 42, 44, 92, 96, 102, 0, 
	31, 33, 39, 46, 47, 59, 63, 91, 
	94, 123, 127, 42, 44, 92, 96, 105, 
	0, 31, 33, 39, 46, 47, 48, 57, 
	59, 63, 91, 94, 123, 127, 42, 44, 
	46, 47, 69, 92, 96, 101, 0, 31, 
	33, 39, 48, 57, 59, 63, 91, 94, 
	123, 127, 42, 69, 101, 48, 57, 42, 
	48, 57, 42, 45, 92, 96, 0, 31, 
	33, 39, 44, 47, 48, 57, 59, 63, 
	91, 94, 123, 127, 42, 44, 92, 96, 
	0, 31, 33, 39, 46, 47, 48, 57, 
	59, 63, 91, 94, 123, 127, 42, 44, 
	92, 96, 0, 31, 33, 39, 46, 47, 
	48, 57, 59, 63, 91, 94, 123, 127, 
	32, 42, 44, 46, 47, 58, 64, 69, 
	92, 96, 101, 0, 39, 40, 45, 48, 
	57, 59, 63, 91, 94, 123, 127, 32, 
	42, 45, 58, 64, 92, 96, 0, 39, 
	40, 43, 44, 47, 48, 57, 59, 63, 
	91, 94, 123, 127, 32, 42, 44, 58, 
	64, 92, 96, 0, 39, 40, 45, 46, 
	47, 48, 57, 59, 63, 91, 94, 123, 
	127, 42, 44, 62, 92, 96, 0, 31, 
	33, 39, 46, 47, 59, 63, 91, 94, 
	123, 127, 92, 96, 0, 47, 58, 64, 
	91, 94, 123, 127, 32, 42, 44, 58, 
	64, 92, 95, 127, 0, 8, 9, 13, 
	14, 31, 33, 39, 40, 45, 46, 47, 
	59, 63, 91, 96, 123, 126, 32, 42, 
	44, 58, 64, 92, 96, 102, 0, 39, 
	40, 45, 46, 47, 59, 63, 91, 94, 
	123, 127, 0
};

static const char _query_single_lengths[] = {
	0, 7, 1, 3, 3, 0, 3, 0, 
	2, 0, 1, 3, 0, 2, 0, 0, 
	1, 0, 0, 1, 0, 0, 9, 4, 
	8, 8, 2, 2, 0, 28, 7, 4, 
	7, 7, 3, 6, 5, 6, 6, 8, 
	7, 3, 3, 4, 8, 3, 1, 4, 
	4, 4, 11, 7, 5, 5, 5, 5, 
	8, 3, 1, 4, 4, 4, 11, 7, 
	7, 5, 2, 8, 8
};

static const char _query_range_lengths[] = {
	0, 6, 1, 5, 4, 5, 5, 5, 
	0, 0, 1, 5, 5, 4, 5, 1, 
	1, 1, 1, 1, 1, 5, 6, 5, 
	6, 6, 0, 0, 0, 7, 6, 6, 
	6, 6, 4, 6, 6, 6, 6, 7, 
	6, 4, 4, 7, 6, 1, 1, 7, 
	7, 7, 6, 6, 6, 6, 6, 7, 
	6, 1, 1, 7, 7, 7, 6, 7, 
	7, 6, 4, 9, 6
};

static const short _query_index_offsets[] = {
	0, 0, 14, 17, 26, 34, 40, 49, 
	55, 58, 59, 62, 71, 77, 84, 90, 
	92, 95, 97, 99, 102, 104, 110, 126, 
	136, 151, 166, 169, 172, 173, 209, 223, 
	234, 248, 262, 270, 283, 295, 308, 321, 
	337, 351, 359, 367, 379, 394, 399, 402, 
	414, 426, 438, 456, 470, 482, 494, 506, 
	519, 534, 539, 542, 554, 566, 578, 596, 
	611, 626, 638, 645, 663
};

static const char _query_indicies[] = {
	1, 3, 2, 1, 1, 4, 2, 2, 
	1, 2, 2, 2, 2, 0, 1, 1, 
	5, 0, 6, 6, 6, 6, 6, 6, 
	0, 5, 3, 7, 5, 5, 5, 5, 
	5, 6, 6, 6, 6, 6, 6, 5, 
	9, 8, 8, 8, 8, 8, 8, 9, 
	5, 8, 8, 8, 8, 8, 10, 12, 
	13, 11, 11, 14, 14, 11, 16, 15, 
	15, 15, 15, 15, 15, 16, 5, 15, 
	15, 15, 15, 15, 17, 20, 18, 18, 
	18, 18, 18, 19, 19, 19, 19, 19, 
	19, 5, 22, 21, 23, 24, 17, 24, 
	17, 25, 5, 27, 28, 26, 28, 26, 
	29, 29, 29, 29, 29, 5, 1, 3, 
	2, 1, 1, 30, 4, 2, 30, 2, 
	1, 2, 2, 2, 2, 0, 3, 31, 
	5, 5, 5, 5, 5, 1, 5, 6, 
	1, 3, 2, 1, 1, 4, 2, 32, 
	2, 1, 2, 2, 2, 2, 0, 1, 
	33, 3, 2, 1, 1, 4, 2, 2, 
	1, 2, 2, 2, 2, 0, 2, 35, 
	34, 36, 35, 34, 34, 39, 41, 42, 
	43, 44, 45, 46, 47, 48, 49, 50, 
	52, 53, 54, 55, 56, 57, 58, 59, 
	60, 56, 61, 62, 63, 64, 65, 66, 
	38, 38, 39, 38, 40, 51, 40, 40, 
	37, 1, 3, 5, 1, 1, 4, 5, 
	5, 1, 5, 5, 5, 5, 0, 5, 
	5, 67, 5, 5, 5, 5, 5, 5, 
	5, 1, 1, 68, 68, 1, 1, 69, 
	68, 68, 1, 68, 68, 68, 68, 9, 
	1, 3, 70, 1, 1, 69, 70, 70, 
	1, 70, 70, 70, 70, 9, 3, 71, 
	70, 70, 70, 70, 70, 8, 68, 11, 
	11, 72, 11, 73, 11, 11, 11, 11, 
	11, 11, 14, 12, 11, 11, 72, 11, 
	11, 11, 11, 11, 11, 11, 14, 12, 
	11, 11, 72, 11, 75, 11, 11, 11, 
	11, 11, 11, 14, 12, 11, 11, 72, 
	11, 76, 11, 11, 11, 11, 11, 11, 
	14, 1, 78, 77, 79, 1, 1, 81, 
	77, 77, 1, 77, 80, 77, 77, 77, 
	16, 1, 82, 74, 1, 1, 81, 74, 
	74, 1, 74, 74, 74, 74, 16, 82, 
	84, 83, 83, 83, 83, 83, 15, 82, 
	20, 83, 83, 83, 83, 83, 19, 74, 
	74, 67, 74, 74, 74, 74, 85, 74, 
	74, 74, 1, 82, 74, 86, 74, 87, 
	67, 74, 87, 74, 74, 85, 74, 74, 
	74, 1, 82, 88, 88, 22, 83, 82, 
	24, 83, 74, 89, 67, 74, 74, 74, 
	74, 90, 74, 74, 74, 1, 74, 74, 
	67, 74, 74, 74, 74, 90, 74, 74, 
	74, 1, 82, 74, 67, 74, 74, 74, 
	74, 90, 74, 74, 74, 1, 1, 82, 
	74, 86, 74, 1, 1, 91, 81, 74, 
	91, 74, 1, 80, 74, 74, 74, 16, 
	1, 82, 89, 1, 1, 81, 74, 74, 
	1, 74, 74, 74, 74, 16, 68, 68, 
	67, 68, 92, 68, 68, 68, 68, 68, 
	68, 1, 74, 74, 67, 74, 93, 74, 
	74, 74, 74, 74, 74, 1, 74, 74, 
	67, 74, 94, 74, 74, 74, 74, 74, 
	74, 1, 95, 95, 67, 95, 92, 95, 
	95, 95, 96, 95, 95, 95, 1, 3, 
	97, 98, 97, 99, 67, 97, 99, 97, 
	97, 96, 97, 97, 97, 1, 3, 100, 
	100, 25, 97, 3, 28, 97, 74, 101, 
	67, 74, 74, 74, 74, 102, 74, 74, 
	74, 1, 74, 74, 67, 74, 74, 74, 
	74, 102, 74, 74, 74, 1, 3, 97, 
	67, 97, 97, 97, 97, 102, 97, 97, 
	97, 1, 1, 3, 103, 98, 103, 1, 
	1, 104, 4, 103, 104, 103, 1, 51, 
	103, 103, 103, 0, 1, 3, 101, 1, 
	1, 4, 74, 74, 1, 74, 105, 74, 
	74, 74, 0, 1, 3, 97, 1, 1, 
	4, 97, 97, 1, 97, 105, 97, 97, 
	97, 0, 68, 68, 106, 67, 68, 68, 
	68, 68, 68, 68, 68, 1, 107, 5, 
	5, 5, 5, 5, 29, 0, 6, 6, 
	0, 0, 108, 0, 5, 5, 6, 5, 
	6, 0, 6, 6, 6, 6, 1, 1, 
	3, 74, 1, 1, 4, 74, 109, 74, 
	1, 74, 74, 74, 74, 0, 0
};

static const char _query_trans_targs[] = {
	30, 31, 0, 29, 3, 29, 4, 5, 
	34, 33, 29, 8, 29, 9, 36, 41, 
	40, 29, 29, 42, 14, 29, 45, 17, 
	46, 57, 29, 20, 58, 66, 30, 67, 
	68, 26, 27, 28, 29, 1, 31, 31, 
	31, 31, 32, 31, 35, 31, 31, 39, 
	52, 29, 55, 62, 29, 31, 65, 66, 
	22, 31, 67, 31, 30, 24, 25, 29, 
	29, 31, 31, 2, 29, 6, 29, 7, 
	10, 37, 29, 38, 36, 29, 13, 43, 
	50, 11, 29, 29, 12, 44, 15, 47, 
	16, 48, 49, 51, 53, 54, 31, 29, 
	56, 29, 18, 59, 19, 60, 61, 29, 
	63, 64, 29, 21, 23, 30
};

static const char _query_trans_actions[] = {
	114, 114, 0, 15, 0, 49, 0, 0, 
	3, 63, 41, 0, 19, 0, 114, 3, 
	114, 47, 43, 117, 0, 45, 3, 0, 
	0, 3, 39, 0, 0, 60, 66, 114, 
	114, 0, 0, 0, 21, 0, 111, 105, 
	108, 72, 108, 96, 108, 75, 78, 93, 
	108, 13, 87, 54, 11, 84, 108, 108, 
	0, 99, 108, 102, 108, 0, 0, 9, 
	7, 81, 90, 0, 33, 0, 27, 0, 
	0, 114, 35, 114, 69, 31, 0, 114, 
	114, 0, 17, 37, 0, 114, 0, 114, 
	0, 114, 114, 114, 114, 114, 69, 29, 
	57, 25, 0, 114, 0, 114, 57, 23, 
	114, 57, 5, 0, 0, 69
};

static const char _query_to_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 51, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0
};

static const char _query_from_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 1, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0
};

static const short _query_eof_trans[] = {
	0, 0, 6, 6, 6, 6, 6, 11, 
	6, 6, 6, 6, 18, 19, 6, 22, 
	18, 18, 6, 27, 27, 6, 0, 6, 
	0, 0, 0, 0, 0, 0, 6, 6, 
	69, 71, 71, 69, 6, 75, 75, 78, 
	75, 84, 84, 75, 75, 84, 84, 75, 
	75, 75, 75, 75, 69, 75, 75, 96, 
	98, 98, 98, 75, 75, 98, 104, 75, 
	98, 69, 6, 6, 75
};

static const int query_start = 29;
static const int query_first_final = 29;
static const int query_error = 0;

static const int query_en_main = 29;


/* #line 330 "lexer.rl" */

QueryNode *RSQuery_ParseRaw_v2(QueryParseCtx *q) {
  void *pParser = RSQuery_ParseAlloc_v2(rm_malloc);

  
  int cs, act;
  const char* ts = q->raw;
  const char* te = q->raw + q->len;
  
/* #line 398 "lexer.c" */
	{
	cs = query_start;
	ts = 0;
	te = 0;
	act = 0;
	}

/* #line 339 "lexer.rl" */
  QueryToken tok = {.len = 0, .pos = 0, .s = 0};
  
  //parseCtx ctx = {.root = NULL, .ok = 1, .errorMsg = NULL, .q = q};
  const char* p = q->raw;
  const char* pe = q->raw + q->len;
  const char* eof = pe;
  
  
/* #line 415 "lexer.c" */
	{
	int _klen;
	unsigned int _trans;
	const char *_acts;
	unsigned int _nacts;
	const char *_keys;

	if ( p == pe )
		goto _test_eof;
	if ( cs == 0 )
		goto _out;
_resume:
	_acts = _query_actions + _query_from_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 2:
/* #line 1 "NONE" */
	{ts = p;}
	break;
/* #line 436 "lexer.c" */
		}
	}

	_keys = _query_trans_keys + _query_key_offsets[cs];
	_trans = _query_index_offsets[cs];

	_klen = _query_single_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + _klen - 1;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( (*p) < *_mid )
				_upper = _mid - 1;
			else if ( (*p) > *_mid )
				_lower = _mid + 1;
			else {
				_trans += (unsigned int)(_mid - _keys);
				goto _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _query_range_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + (_klen<<1) - 2;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( (*p) < _mid[0] )
				_upper = _mid - 2;
			else if ( (*p) > _mid[1] )
				_lower = _mid + 2;
			else {
				_trans += (unsigned int)((_mid - _keys)>>1);
				goto _match;
			}
		}
		_trans += _klen;
	}

_match:
	_trans = _query_indicies[_trans];
_eof_trans:
	cs = _query_trans_targs[_trans];

	if ( _query_trans_actions[_trans] == 0 )
		goto _again;

	_acts = _query_actions + _query_trans_actions[_trans];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 )
	{
		switch ( *_acts++ )
		{
	case 3:
/* #line 1 "NONE" */
	{te = p+1;}
	break;
	case 4:
/* #line 69 "lexer.rl" */
	{act = 1;}
	break;
	case 5:
/* #line 80 "lexer.rl" */
	{act = 2;}
	break;
	case 6:
/* #line 91 "lexer.rl" */
	{act = 3;}
	break;
	case 7:
/* #line 100 "lexer.rl" */
	{act = 4;}
	break;
	case 8:
/* #line 118 "lexer.rl" */
	{act = 6;}
	break;
	case 9:
/* #line 127 "lexer.rl" */
	{act = 7;}
	break;
	case 10:
/* #line 138 "lexer.rl" */
	{act = 8;}
	break;
	case 11:
/* #line 152 "lexer.rl" */
	{act = 10;}
	break;
	case 12:
/* #line 160 "lexer.rl" */
	{act = 11;}
	break;
	case 13:
/* #line 175 "lexer.rl" */
	{act = 13;}
	break;
	case 14:
/* #line 191 "lexer.rl" */
	{act = 15;}
	break;
	case 15:
/* #line 200 "lexer.rl" */
	{act = 16;}
	break;
	case 16:
/* #line 207 "lexer.rl" */
	{act = 17;}
	break;
	case 17:
/* #line 214 "lexer.rl" */
	{act = 18;}
	break;
	case 18:
/* #line 221 "lexer.rl" */
	{act = 19;}
	break;
	case 19:
/* #line 228 "lexer.rl" */
	{act = 20;}
	break;
	case 20:
/* #line 235 "lexer.rl" */
	{act = 21;}
	break;
	case 21:
/* #line 242 "lexer.rl" */
	{act = 22;}
	break;
	case 22:
/* #line 243 "lexer.rl" */
	{act = 23;}
	break;
	case 23:
/* #line 244 "lexer.rl" */
	{act = 24;}
	break;
	case 24:
/* #line 246 "lexer.rl" */
	{act = 25;}
	break;
	case 25:
/* #line 271 "lexer.rl" */
	{act = 27;}
	break;
	case 26:
/* #line 109 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ARROW, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 27:
/* #line 145 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, OR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 28:
/* #line 167 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    printf("lb: %.*s\n", (int)(te-ts), ts);
    RSQuery_Parse_v2(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 29:
/* #line 183 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    printf("colon: %.*s\n", (int)(te-ts), ts);
    RSQuery_Parse_v2(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 30:
/* #line 243 "lexer.rl" */
	{te = p+1;}
	break;
	case 31:
/* #line 257 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*ts == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("prefix: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, PREFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 32:
/* #line 285 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, CONTAINS, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 33:
/* #line 300 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    RSQuery_Parse_v2(pParser, VERBATIM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 34:
/* #line 313 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_WILDCARD : QT_WILDCARD;
    tok.pos = ts-q->raw + 2;
    tok.len = te - (ts + 3 + is_attr);
    tok.s = ts + 2 + is_attr;
    tok.numval = 0;
    RSQuery_Parse_v2(pParser, WILDCARD, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 35:
/* #line 69 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 36:
/* #line 80 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 37:
/* #line 100 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 38:
/* #line 200 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 39:
/* #line 214 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 40:
/* #line 243 "lexer.rl" */
	{te = p;p--;}
	break;
	case 41:
/* #line 246 "lexer.rl" */
	{te = p;p--;{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("escaped term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 42:
/* #line 271 "lexer.rl" */
	{te = p;p--;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("suffix: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 43:
/* #line 80 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 44:
/* #line 100 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 45:
/* #line 214 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 46:
/* #line 246 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("escaped term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 47:
/* #line 271 "lexer.rl" */
	{{p = ((te))-1;}{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("suffix: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 48:
/* #line 1 "NONE" */
	{	switch( act ) {
	case 0:
	{{cs = 0;goto _again;}}
	break;
	case 1:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 2:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 3:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, MODIFIER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 4:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 6:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts;
    RSQuery_Parse_v2(pParser, AS_T, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 7:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 8:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, QUOTE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 10:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 11:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 13:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    printf("rb: %.*s\n", (int)(te-ts), ts);
    RSQuery_Parse_v2(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 15:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    printf("semicolon: %.*s\n", (int)(te-ts), ts);
    RSQuery_Parse_v2(pParser, SEMICOLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }
	break;
	case 16:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 17:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, TILDE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 18:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 19:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, PERCENT, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 20:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LSQB, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }  
  }
	break;
	case 21:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RSQB, tok, q);   
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    } 
  }
	break;
	case 25:
	{{p = ((te))-1;}
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("escaped term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 27:
	{{p = ((te))-1;}
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("suffix: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	default:
	{{p = ((te))-1;}}
	break;
	}
	}
	break;
/* #line 1081 "lexer.c" */
		}
	}

_again:
	_acts = _query_actions + _query_to_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 0:
/* #line 1 "NONE" */
	{ts = 0;}
	break;
	case 1:
/* #line 1 "NONE" */
	{act = 0;}
	break;
/* #line 1098 "lexer.c" */
		}
	}

	if ( cs == 0 )
		goto _out;
	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	if ( _query_eof_trans[cs] > 0 ) {
		_trans = _query_eof_trans[cs] - 1;
		goto _eof_trans;
	}
	}

	_out: {}
	}

/* #line 347 "lexer.rl" */
  
  if (QPCTX_ISOK(q)) {
    RSQuery_Parse_v2(pParser, 0, tok, q);
  }
  RSQuery_ParseFree_v2(pParser, rm_free);
  if (!QPCTX_ISOK(q) && q->root) {
    QueryNode_Free(q->root);
    q->root = NULL;
  }
  return q->root;
}

