
/* #line 1 "lexer.rl" */
/*
 * Copyright Redis Ltd. 2016 - present
 * Licensed under your choice of the Redis Source Available License 2.0 (RSALv2) or
 * the Server Side Public License v1 (SSPLv1).
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>

#include "../parse.h"
#include "parser.h"
#include "../../query_node.h"
#include "../../stopwords.h"

/* forward declarations of stuff generated by lemon */

#define RSQuery_Parse_v2 RSQueryParser_v2_ // weird Lemon quirk.. oh well..
#define RSQuery_ParseAlloc_v2 RSQueryParser_v2_Alloc
#define RSQuery_ParseFree_v2 RSQueryParser_v2_Free

void RSQuery_Parse_v2(void *yyp, int yymajor, QueryToken yyminor, QueryParseCtx *ctx);
void *RSQuery_ParseAlloc_v2(void *(*mallocProc)(size_t));
void RSQuery_ParseFree_v2(void *p, void (*freeProc)(void *));


/* #line 339 "lexer.rl" */



/* #line 36 "lexer.c" */
static const char _query_actions[] = {
	0, 1, 0, 1, 1, 1, 2, 1, 
	14, 1, 15, 1, 16, 1, 17, 1, 
	18, 1, 19, 1, 20, 1, 21, 1, 
	22, 1, 23, 1, 24, 1, 25, 1, 
	26, 1, 27, 1, 28, 1, 29, 1, 
	30, 1, 31, 1, 32, 1, 33, 1, 
	34, 1, 35, 1, 36, 1, 37, 1, 
	38, 1, 39, 1, 40, 1, 41, 1, 
	42, 1, 43, 1, 44, 1, 45, 1, 
	46, 1, 47, 1, 48, 1, 49, 1, 
	50, 2, 2, 3, 2, 2, 4, 2, 
	2, 5, 2, 2, 6, 2, 2, 7, 
	2, 2, 8, 2, 2, 9, 2, 2, 
	10, 2, 2, 11, 2, 2, 12, 2, 
	2, 13
};

static const short _query_key_offsets[] = {
	0, 10, 20, 22, 22, 25, 28, 38, 
	48, 50, 52, 55, 57, 58, 59, 61, 
	64, 66, 76, 78, 80, 80, 82, 84, 
	84, 126, 137, 147, 158, 161, 163, 177, 
	188, 194, 199, 202, 218, 230, 231, 234, 
	240, 245, 248, 264, 278, 291, 292, 302, 
	315, 325, 337, 349, 361
};

static const char _query_trans_keys[] = {
	9, 13, 32, 47, 58, 64, 91, 96, 
	123, 126, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 39, 92, 39, 92, 
	110, 39, 92, 102, 9, 13, 32, 47, 
	58, 64, 91, 96, 123, 126, 92, 96, 
	0, 47, 58, 64, 91, 94, 123, 127, 
	48, 57, 48, 57, 45, 48, 57, 48, 
	57, 110, 102, 48, 57, 45, 48, 57, 
	48, 57, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 39, 92, 39, 92, 
	39, 92, 39, 92, 32, 34, 36, 37, 
	39, 40, 41, 42, 43, 45, 58, 59, 
	61, 64, 65, 91, 92, 93, 95, 97, 
	105, 114, 119, 123, 124, 125, 126, 127, 
	0, 8, 9, 13, 14, 31, 33, 47, 
	48, 57, 60, 63, 94, 96, 42, 92, 
	96, 0, 47, 58, 64, 91, 94, 123, 
	127, 92, 96, 0, 47, 58, 64, 91, 
	94, 123, 127, 42, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 39, 92, 
	105, 39, 92, 36, 45, 92, 96, 0, 
	47, 48, 57, 58, 64, 91, 94, 123, 
	127, 42, 92, 96, 0, 47, 58, 64, 
	91, 94, 123, 127, 42, 46, 69, 101, 
	48, 57, 42, 69, 101, 48, 57, 42, 
	48, 57, 42, 46, 69, 92, 96, 101, 
	0, 47, 48, 57, 58, 64, 91, 94, 
	123, 127, 42, 45, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 105, 105, 
	48, 57, 42, 46, 69, 101, 48, 57, 
	42, 69, 101, 48, 57, 42, 48, 57, 
	42, 46, 69, 92, 96, 101, 0, 47, 
	48, 57, 58, 64, 91, 94, 123, 127, 
	42, 45, 92, 96, 0, 47, 48, 57, 
	58, 64, 91, 94, 123, 127, 42, 92, 
	96, 0, 47, 48, 57, 58, 64, 91, 
	94, 123, 127, 62, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 42, 83, 
	92, 96, 115, 0, 47, 58, 64, 91, 
	94, 123, 127, 9, 13, 32, 47, 58, 
	64, 91, 96, 123, 126, 42, 92, 96, 
	110, 0, 47, 58, 64, 91, 94, 123, 
	127, 42, 92, 96, 102, 0, 47, 58, 
	64, 91, 94, 123, 127, 39, 42, 92, 
	96, 0, 47, 58, 64, 91, 94, 123, 
	127, 39, 42, 92, 96, 0, 47, 58, 
	64, 91, 94, 123, 127, 0
};

static const char _query_single_lengths[] = {
	0, 0, 2, 0, 3, 3, 0, 2, 
	0, 0, 1, 0, 1, 1, 0, 1, 
	0, 0, 2, 2, 0, 2, 2, 0, 
	28, 3, 2, 3, 3, 2, 4, 3, 
	4, 3, 1, 6, 4, 1, 1, 4, 
	3, 1, 6, 4, 3, 1, 2, 5, 
	0, 4, 4, 4, 4
};

static const char _query_range_lengths[] = {
	5, 5, 0, 0, 0, 0, 5, 4, 
	1, 1, 1, 1, 0, 0, 1, 1, 
	1, 5, 0, 0, 0, 0, 0, 0, 
	7, 4, 4, 4, 0, 0, 5, 4, 
	1, 1, 1, 5, 4, 0, 1, 1, 
	1, 1, 5, 5, 5, 0, 4, 4, 
	5, 4, 4, 4, 4
};

static const short _query_index_offsets[] = {
	0, 6, 12, 15, 16, 20, 24, 30, 
	37, 39, 41, 44, 46, 48, 50, 52, 
	55, 57, 63, 66, 69, 70, 73, 76, 
	77, 113, 121, 128, 136, 140, 143, 153, 
	161, 167, 172, 175, 187, 196, 198, 201, 
	207, 212, 215, 227, 237, 246, 248, 255, 
	265, 271, 280, 289, 298
};

static const char _query_indicies[] = {
	1, 1, 1, 1, 1, 0, 2, 2, 
	2, 2, 2, 0, 4, 5, 3, 3, 
	4, 5, 7, 3, 4, 5, 8, 3, 
	9, 9, 9, 9, 9, 0, 11, 10, 
	10, 10, 10, 10, 9, 12, 10, 14, 
	13, 15, 16, 13, 16, 13, 17, 0, 
	18, 0, 19, 0, 21, 22, 20, 22, 
	0, 23, 23, 23, 23, 23, 0, 24, 
	26, 25, 27, 26, 25, 25, 24, 29, 
	28, 30, 29, 28, 28, 32, 34, 35, 
	36, 37, 38, 39, 40, 41, 42, 44, 
	45, 46, 47, 48, 49, 50, 51, 52, 
	48, 53, 54, 55, 56, 57, 58, 59, 
	31, 31, 32, 31, 33, 43, 33, 33, 
	1, 60, 61, 0, 0, 0, 0, 0, 
	1, 63, 62, 62, 62, 62, 62, 2, 
	60, 63, 64, 64, 64, 64, 64, 2, 
	62, 5, 65, 3, 4, 5, 3, 68, 
	69, 11, 67, 67, 70, 67, 67, 67, 
	9, 72, 11, 71, 71, 71, 71, 71, 
	9, 72, 73, 74, 74, 12, 71, 72, 
	74, 74, 14, 71, 72, 16, 71, 72, 
	73, 75, 11, 71, 75, 71, 70, 71, 
	71, 71, 9, 72, 15, 11, 71, 71, 
	71, 71, 71, 9, 76, 62, 76, 78, 
	77, 60, 80, 81, 81, 78, 79, 60, 
	81, 81, 19, 79, 60, 22, 79, 60, 
	80, 83, 61, 82, 83, 82, 43, 82, 
	82, 82, 1, 60, 21, 61, 84, 84, 
	85, 84, 84, 84, 1, 60, 61, 79, 
	79, 85, 79, 79, 79, 1, 86, 62, 
	87, 0, 0, 0, 0, 0, 23, 60, 
	88, 61, 84, 88, 84, 84, 84, 84, 
	1, 1, 1, 1, 1, 1, 62, 60, 
	61, 84, 89, 84, 84, 84, 84, 1, 
	60, 61, 84, 90, 84, 84, 84, 84, 
	1, 91, 60, 61, 84, 84, 84, 84, 
	84, 1, 92, 60, 61, 84, 84, 84, 
	84, 84, 1, 0
};

static const char _query_trans_targs[] = {
	24, 25, 27, 2, 24, 3, 24, 5, 
	29, 31, 24, 6, 32, 24, 33, 11, 
	34, 13, 24, 40, 24, 16, 41, 46, 
	24, 19, 20, 24, 22, 23, 24, 24, 
	24, 24, 24, 26, 24, 28, 24, 24, 
	30, 37, 38, 42, 24, 24, 45, 46, 
	47, 24, 48, 24, 25, 49, 51, 52, 
	24, 24, 24, 24, 24, 0, 24, 1, 
	24, 4, 24, 24, 7, 8, 35, 24, 
	24, 9, 10, 36, 12, 24, 39, 24, 
	14, 15, 24, 43, 24, 44, 24, 17, 
	25, 50, 25, 18, 21
};

static const char _query_trans_actions[] = {
	79, 108, 90, 0, 45, 0, 73, 0, 
	96, 111, 71, 0, 5, 77, 5, 0, 
	0, 0, 9, 84, 69, 0, 0, 87, 
	75, 0, 0, 49, 0, 0, 47, 39, 
	35, 37, 11, 105, 29, 105, 15, 17, 
	102, 105, 99, 81, 23, 25, 0, 105, 
	108, 31, 0, 33, 105, 108, 108, 108, 
	19, 13, 21, 27, 41, 0, 63, 0, 
	55, 0, 57, 61, 0, 0, 111, 67, 
	43, 0, 0, 111, 0, 59, 84, 53, 
	0, 0, 51, 108, 65, 84, 7, 0, 
	93, 108, 96, 0, 0
};

static const char _query_to_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	1, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0
};

static const char _query_from_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	3, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0
};

static const short _query_eof_trans[] = {
	1, 1, 1, 1, 7, 7, 1, 11, 
	11, 14, 14, 14, 1, 1, 1, 21, 
	1, 1, 25, 25, 25, 25, 25, 25, 
	0, 1, 63, 65, 63, 67, 68, 72, 
	72, 72, 72, 72, 72, 63, 78, 80, 
	80, 80, 83, 85, 80, 63, 1, 85, 
	63, 85, 85, 85, 85
};

static const int query_start = 24;
static const int query_first_final = 24;
static const int query_error = -1;

static const int query_en_main = 24;


/* #line 342 "lexer.rl" */

QueryNode *RSQuery_ParseRaw_v2(QueryParseCtx *q) {
  void *pParser = RSQuery_ParseAlloc_v2(rm_malloc);

  
  int cs, act;
  const char* ts = q->raw;
  const char* te = q->raw + q->len;
  
/* #line 264 "lexer.c" */
	{
	cs = query_start;
	ts = 0;
	te = 0;
	act = 0;
	}

/* #line 351 "lexer.rl" */
  QueryToken tok = {.len = 0, .pos = 0, .s = 0};
  
  //parseCtx ctx = {.root = NULL, .ok = 1, .errorMsg = NULL, .q = q};
  const char* p = q->raw;
  const char* pe = q->raw + q->len;
  const char* eof = pe;
  
  
/* #line 281 "lexer.c" */
	{
	int _klen;
	unsigned int _trans;
	const char *_acts;
	unsigned int _nacts;
	const char *_keys;

	if ( p == pe )
		goto _test_eof;
_resume:
	_acts = _query_actions + _query_from_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 1:
/* #line 1 "NONE" */
	{ts = p;}
	break;
/* #line 300 "lexer.c" */
		}
	}

	_keys = _query_trans_keys + _query_key_offsets[cs];
	_trans = _query_index_offsets[cs];

	_klen = _query_single_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + _klen - 1;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( (*p) < *_mid )
				_upper = _mid - 1;
			else if ( (*p) > *_mid )
				_lower = _mid + 1;
			else {
				_trans += (unsigned int)(_mid - _keys);
				goto _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _query_range_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + (_klen<<1) - 2;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( (*p) < _mid[0] )
				_upper = _mid - 2;
			else if ( (*p) > _mid[1] )
				_lower = _mid + 2;
			else {
				_trans += (unsigned int)((_mid - _keys)>>1);
				goto _match;
			}
		}
		_trans += _klen;
	}

_match:
	_trans = _query_indicies[_trans];
_eof_trans:
	cs = _query_trans_targs[_trans];

	if ( _query_trans_actions[_trans] == 0 )
		goto _again;

	_acts = _query_actions + _query_trans_actions[_trans];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 )
	{
		switch ( *_acts++ )
		{
	case 2:
/* #line 1 "NONE" */
	{te = p+1;}
	break;
	case 3:
/* #line 67 "lexer.rl" */
	{act = 1;}
	break;
	case 4:
/* #line 78 "lexer.rl" */
	{act = 2;}
	break;
	case 5:
/* #line 89 "lexer.rl" */
	{act = 3;}
	break;
	case 6:
/* #line 99 "lexer.rl" */
	{act = 4;}
	break;
	case 7:
/* #line 118 "lexer.rl" */
	{act = 6;}
	break;
	case 8:
/* #line 127 "lexer.rl" */
	{act = 7;}
	break;
	case 9:
/* #line 196 "lexer.rl" */
	{act = 16;}
	break;
	case 10:
/* #line 210 "lexer.rl" */
	{act = 18;}
	break;
	case 11:
/* #line 239 "lexer.rl" */
	{act = 23;}
	break;
	case 12:
/* #line 242 "lexer.rl" */
	{act = 25;}
	break;
	case 13:
/* #line 267 "lexer.rl" */
	{act = 27;}
	break;
	case 14:
/* #line 109 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ARROW, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 15:
/* #line 127 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 16:
/* #line 138 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, QUOTE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 17:
/* #line 145 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, OR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 18:
/* #line 152 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 19:
/* #line 160 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 20:
/* #line 167 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 21:
/* #line 174 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 22:
/* #line 181 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v2(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 23:
/* #line 188 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v2(pParser, SEMICOLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 24:
/* #line 203 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, TILDE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 25:
/* #line 217 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, PERCENT, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 26:
/* #line 224 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LSQB, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }  
  }}
	break;
	case 27:
/* #line 231 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RSQB, tok, q);   
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    } 
  }}
	break;
	case 28:
/* #line 238 "lexer.rl" */
	{te = p+1;}
	break;
	case 29:
/* #line 239 "lexer.rl" */
	{te = p+1;}
	break;
	case 30:
/* #line 240 "lexer.rl" */
	{te = p+1;}
	break;
	case 31:
/* #line 253 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*ts == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, PREFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 32:
/* #line 281 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, CONTAINS, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 33:
/* #line 296 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    printf("verbatim: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, VERBATIM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 34:
/* #line 310 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_WILDCARD : QT_WILDCARD;
    tok.pos = ts-q->raw + 2;
    tok.len = te - (ts + 3 + is_attr);
    tok.s = ts + 2 + is_attr;
    tok.numval = 0;
    printf("wildcard: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, WILDCARD, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 35:
/* #line 324 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+2) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_RAW_STRING : QT_RAW_STRING;
    tok.pos = ts-q->raw + 2;
    tok.len = te - (ts + 3 + is_attr);
    tok.s = ts + 2 + is_attr;
    tok.numval = 0;
    printf("raw_string: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, RAW_STRING, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 36:
/* #line 67 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 37:
/* #line 78 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 38:
/* #line 99 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    printf("attr: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 39:
/* #line 127 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 40:
/* #line 196 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 41:
/* #line 210 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 42:
/* #line 239 "lexer.rl" */
	{te = p;p--;}
	break;
	case 43:
/* #line 242 "lexer.rl" */
	{te = p;p--;{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 44:
/* #line 267 "lexer.rl" */
	{te = p;p--;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 45:
/* #line 78 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 46:
/* #line 210 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 47:
/* #line 239 "lexer.rl" */
	{{p = ((te))-1;}}
	break;
	case 48:
/* #line 242 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 49:
/* #line 267 "lexer.rl" */
	{{p = ((te))-1;}{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 50:
/* #line 1 "NONE" */
	{	switch( act ) {
	case 1:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 2:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 3:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    printf("mod: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, MODIFIER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 4:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    printf("attr: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 6:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts;
    RSQuery_Parse_v2(pParser, AS_T, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 7:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 16:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 18:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 25:
	{{p = ((te))-1;}
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    printf("term: %.*s\n", (int)tok.len, tok.s);
    RSQuery_Parse_v2(pParser, TERM, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 27:
	{{p = ((te))-1;}
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	default:
	{{p = ((te))-1;}}
	break;
	}
	}
	break;
/* #line 950 "lexer.c" */
		}
	}

_again:
	_acts = _query_actions + _query_to_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 0:
/* #line 1 "NONE" */
	{ts = 0;}
	break;
/* #line 963 "lexer.c" */
		}
	}

	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	if ( _query_eof_trans[cs] > 0 ) {
		_trans = _query_eof_trans[cs] - 1;
		goto _eof_trans;
	}
	}

	_out: {}
	}

/* #line 359 "lexer.rl" */
  
  if (QPCTX_ISOK(q)) {
    RSQuery_Parse_v2(pParser, 0, tok, q);
  }
  RSQuery_ParseFree_v2(pParser, rm_free);
  if (!QPCTX_ISOK(q) && q->root) {
    QueryNode_Free(q->root);
    q->root = NULL;
  }
  return q->root;
}

